services:
  postgres:
    image: postgres:16-alpine
    container_name: task_manager_postgres_stag
    restart: unless-stopped
    environment:
      POSTGRES_DB: task_manager
      POSTGRES_USER: task_manager
      POSTGRES_PASSWORD: Asdfghjkl0
    volumes:
      - ../data/postgres-stag:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U task_manager -d task_manager"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: task_manager_redis_stag
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ../../backend
    container_name: task_manager_backend_stag
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8089
    env_file:
      - ../../backend/.env.staging
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    volumes:
      - ../../backend:/app
      - backend_media_stag:/app/media
      - backend_static_stag:/app/static
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  celery-worker:
    build:
      context: ../../backend
    container_name: task_manager_celery_worker_stag
    command: celery -A core worker --loglevel=info
    env_file:
      - ../../backend/.env.staging
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    volumes:
      - ../../backend:/app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  celery-beat:
    build:
      context: ../../backend
    container_name: task_manager_celery_beat_stag
    command: celery -A core beat --loglevel=info
    env_file:
      - ../../backend/.env.staging
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    volumes:
      - ../../backend:/app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  frontend:
    image: node:20-alpine
    container_name: task_manager_frontend_stag
    working_dir: /app
    command: sh -c "npm install && npm run build && npm run start --hostname 0.0.0.0 --port 3000"
    env_file:
      - ../../frontend/.env.staging
    environment:
      API_BASE_INTERNAL: http://backend:8089
      NODE_ENV: staging
    volumes:
      - ../../frontend:/app
      - frontend_node_modules_stag:/app/node_modules
    depends_on:
      - backend

  nginx:
    image: nginx:1.27-alpine
    container_name: task_manager_nginx_stag
    command: >
      sh -c "
        until nc -z backend 8089; do
          echo 'Waiting for backend...';
          sleep 2;
        done;
        until nc -z frontend 3000; do
          echo 'Waiting for frontend...';
          sleep 2;
        done;
        exec nginx -g 'daemon off;'
      "
    depends_on:
      - backend
      - frontend
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - backend_static_stag:/var/www/backend/static:ro
      - backend_media_stag:/var/www/backend/media:ro

volumes:
  backend_media_stag:
  frontend_node_modules_stag:
  backend_static_stag:

networks:
  default:
    name: task_manager_staging